name: Publish Docker Image
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'    # Para v1.2.3
      - 'v[0-9]+.[0-9]+.[0-9]+-*' # Solo cuando se publica (no pre-releases, etc)

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Necesitamos leer el repo (para el checkout)
      packages: write # Permiso para escribir en registros (si usamos GHCR)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Define Docker tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            juanjogeyer/simplex2
          tags: |
            # Esto crea dos tags:
            type=semver,pattern={{version}}
            type=sha,prefix=latest,suffix=,format=short

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: . # Asume que el Dockerfile está en la raíz
          file: ./Dockerfile # Ruta al Dockerfile
          push: true
          # Usa los tags generados en el paso anterior
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
